### PR TITLE
Update Dockerfile to let tgcrypto build

### PR DESCRIPTION
**Pull request by albertopasqualetto**
Added gcc install

### CODE REVIEW

**Comment by Masterolic** [comment]
Don't know about gcc need to reffer it...thanks for pulling it

**Comment by albertopasqualetto** [comment]
I do not know if it is related to arm architecture.

**Comment by Masterolic** [comment]
Yes got it gcc for c type language we are using python interpreter it's not required but we still use c based libraries for pyrogram making it faster and other to...!

Most of the system its pre-installed anyway I had added to the dockerfile thank you !

**Comment by albertopasqualetto** [comment]
@Masterolic Usually PRs get merged to give the author credits for his commits. Copying code sounds like stealing.

**Pull request closed without merging**
