### PR TITLE
Fix: ERROR: unable to download video data: HTTP Error 403: Forbidden

### PR DESCRIPTION
**Pull request by albertopasqualetto**
Fixed the error on the title with by updating yt-dlp.

### CODE REVIEW

**Comment by Masterolic** [comment]
Thanks :) anyway I had pulled it but those 403 is region based restrictions so...for you it may help with other reasons As My Investigation i had mentioned in readme US REGION Required cookies now

**Comment by albertopasqualetto** [comment]
My VPS is based in Milan, updating yt-dlp, the problem has been solved.

**Comment by albertopasqualetto** [comment]
Why you do not merge the PRs, but instead you copy the change by your own, this is not really optimal, you are not giving credits to other devs...

**Comment by Masterolic** [comment]
Because its not a major change also that does not a fix for 403 as your statement was solving 403 branch 320  req* file was named as yt-dlp itself I had rolled back to the actual file

**Comment by albertopasqualetto** [comment]
This is a very good bot, but what the hell, this is completely nonsense.

Also it is impossible to understand what you are saying.

**Pull request closed without merging**
